[pytest]
# Diz ao pytest que a pasta atual (.) é a raiz para encontrar os imports (como o 'src')
pythonpath = .

# Gerencia automaticamente os testes assíncronos para não gerar avisos
asyncio_mode = auto